### ISSUE TITLE
Vector features documentation discrepancies

### ISSUE THREAD

**Issue by sseiber** [microsoft/AzureDataRetrievalAugmentedGenerationSamples#61]
### Samples in question (two versions of the same sample)
There are two versions of the same sample demonstrating the NoSQL vector features:
  1. [Quickstart - Build a RAG Chatbot | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cosmos-db/gen-ai/quickstart-rag-chatbot)
  1. [AzureDataRetrievalAugmentedGenerationSamples/Python/CosmosDB-NoSQL_VectorSearch/CosmosDB-NoSQL-Quickstart-RAG-Chatbot.ipynb at main · microsoft/AzureDataRetrievalAugmentedGenerationSamples (github.com)](https://github.com/microsoft/AzureDataRetrievalAugmentedGenerationSamples/blob/main/Python/CosmosDB-NoSQL_VectorSearch/CosmosDB-NoSQL-Quickstart-RAG-Chatbot.ipynb)

### Issue 1
These two samples differ in their setup of the vector_embeddings definition. [Sample (1)](https://learn.microsoft.com/en-us/azure/cosmos-db/gen-ai/quickstart-rag-chatbot#3-create-a-database-and-containers-with-vector-policies) uses a distance function of "dotproduct" and sample (2) uses "cosine".

### Issue 2
Sample (2) has "includePaths" and "excludePaths" in the indexing_policy definition.

### Issue 3
There is a function named ["generate_vectors"](https://learn.microsoft.com/en-us/azure/cosmos-db/gen-ai/quickstart-rag-chatbot#6-store-data-in-azure-cosmos-db) that I don't see being called from anywhere but it does seem like it should be called from somewhere.

### Issue 4
There is a command in sample (2) regarding using the sample movie data "as-is" and keeping the vector dimension to "256". However, the [sample data specified in sample (1)](https://learn.microsoft.com/en-us/azure/cosmos-db/gen-ai/quickstart-rag-chatbot#2-initialize-your-client-connection) is from "cosmosdbcosmicworks.blob.core.windows.net..." which doesn't include any pre-defined vectors. When using the "text-3-embedding-large" model with default dimension of 1536 do I need to change the dimension or just generate the vectors using the model's default?

**Comment by TheovanKraay** [comment]
@sseiber thank you for raising these discrepancies. They have been addressed and changes to docs will be deployed soon. To directly address the issues:

Issue 1: both should use cosine
Issue 2: both should have included and excluded paths
Issue 3: correct, it is dormant, both samples have been amended with comments added (docs sample will show up tomorrow).
Issue 4: you should be able to generate the vectors using model's default. If you encounter issues please let us know.
